#!/bin/sh

# build_fat.sh
#
# Created by Robert Carlsen on 15.07.2009.
# build an arm / i686 lib of standard linux project
#
# adopted from: http://latenitesoft.blogspot.com/200...ding-unix.html
#
# initially configured for tesseract-ocr

# Set up the target lib file / path
# easiest to just build the package normally first and watch where the files are created.
LIBFILE=ccmain/libtesseract_full

# Select the desired iPhone SDK
export DEVROOT=/Applications/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
export SDKROOT=$DEVROOT/SDKs/iPhoneOS6.1.sdk

# Set up relevant environment variables
export CPPFLAGS="-I$SDKROOT/usr/llvm-gcc-4.2/lib/gcc/arm-apple-darwin10/4.2.1/include/ -I$SDKROOT/usr/include/"
export CFLAGS="$CPPFLAGS -pipe -no-cpp-precomp -isysroot $SDKROOT"
export CXXFLAGS="$CFLAGS"

# Dynamic library location generated by the Unix package
LIBPATH=$LIBFILE.dylib
LIBNAME=`basename $LIBPATH`

export LDFLAGS="-L$SDKROOT/usr/lib/ -Wl,-dylib_install_name,@executable_path/$LIBNAME"

# Static library that will be generated for ARM
LIBPATH_static=$LIBFILE.a
LIBNAME_static=`basename $LIBPATH_static`

make distclean

echo "ARM COMPILE"
# TODO: add custom flags as necessary for package
./configure --host=arm-apple-darwin --build=i686-apple-darwin11 CXX=$DEVROOT/usr/bin/arm-apple-darwin10-llvm-g++-4.2 CC=$DEVROOT/usr/bin/arm-apple-darwin10-llvm-gcc-4.2 LD=$DEVROOT/usr/bin/ld 

make -j4

# Move the lib to tts location
\rm -rf tts
mkdir tts
mv build/arm-darwin/lib tts/arm-darwin
echo "ARM DONE"

# Do it all again for native cpu
make distclean

# Restore default environment variables
unset CPPFLAGS CFLAGS CPP LDFLAGS CXXFLAGS

export CFLAGS="-arch i386 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/"
# Overwrite LDFLAGS
# Dynamic linking, relative to executable_path
# Use otool -D to check the install name
export LDFLAGS="-arch i386 -Wl,-dylib_install_name,@executable_path/$LIBNAME"

# TODO: error checking
./configure
make -j4

# Move the native library to the tts location
mv build/i386-darwin12.3.0/lib tts/i386-darwin12.3.0

echo "DARWIN DONE"

# Create fat lib by combining the two versions
#$DEVROOT/usr/bin/lipo -arch arm lnsout/$LIBNAME_static.arm -arch i386 lnsout/$LIBNAME_static.i386 -create #-output lnsout/$LIBNAME_static
